package UserStories.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0a = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt_a0a)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Benefit_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Feature_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new FeatureSet_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Goal_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Persona_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5faL), MetaIdFactory.conceptId(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L), MetaIdFactory.conceptId(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325dd247L), MetaIdFactory.conceptId(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5f7L), MetaIdFactory.conceptId(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5f4L)).seal();
}
