package UserStories.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.impl.cellActions.CellAction_DeleteSmart;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;

/*package*/ class Feature_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Feature_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_f5vgr_a();
  }

  private EditorCell createCollection_f5vgr_a() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_f5vgr_a");
    editorCell.setBig(true);
    editorCell.setCellContext(getCellFactory().getCellContext());
    editorCell.addEditorCell(createCollection_f5vgr_a0());
    editorCell.addEditorCell(createCollection_f5vgr_b0());
    editorCell.addEditorCell(createRefNode_f5vgr_c0());
    return editorCell;
  }
  private EditorCell createCollection_f5vgr_a0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_f5vgr_a0");
    editorCell.addEditorCell(createComponent_f5vgr_a0a());
    editorCell.addEditorCell(createProperty_f5vgr_b0a());
    return editorCell;
  }
  private EditorCell createComponent_f5vgr_a0a() {
    EditorCell editorCell = getCellFactory().createEditorComponentCell(myNode, "mpstools.editor.LocalizeableAlias");
    return editorCell;
  }
  private EditorCell createProperty_f5vgr_b0a() {
    CellProviderWithRole provider = new PropertyCellProvider(myNode, getEditorContext());
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createCollection_f5vgr_b0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_f5vgr_b0");
    editorCell.addEditorCell(createCollection_f5vgr_a1a());
    return editorCell;
  }
  private EditorCell createCollection_f5vgr_a1a() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_f5vgr_a1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    style.set(StyleAttributes.INDENT_LAYOUT_INDENT, true);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createRefNode_f5vgr_a0b0());
    editorCell.addEditorCell(createRefNode_f5vgr_b0b0());
    editorCell.addEditorCell(createRefNode_f5vgr_c0b0());
    return editorCell;
  }
  private EditorCell createRefNode_f5vgr_a0b0() {
    SingleRoleCellProvider provider = new Feature_EditorBuilder_a.personaSingleRoleHandler_f5vgr_a0b0(myNode, MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fbL, "persona"), getEditorContext());
    return provider.createCell();
  }
  private static class personaSingleRoleHandler_f5vgr_a0b0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public personaSingleRoleHandler_f5vgr_a0b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fbL, "persona"), child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fbL, "persona"), child));
      installCellInfo(child, editorCell);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new SChildSubstituteInfo(editorCell, myNode, MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fbL, "persona"), child));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("persona");
      }
      Style style = new StyleImpl();
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
      editorCell.getStyle().putAll(style);
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fbL, "persona")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_persona");
        installCellInfo(null, editorCell);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no persona>";
    }
  }
  private EditorCell createRefNode_f5vgr_b0b0() {
    SingleRoleCellProvider provider = new Feature_EditorBuilder_a.goalSingleRoleHandler_f5vgr_b0b0(myNode, MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fdL, "goal"), getEditorContext());
    return provider.createCell();
  }
  private static class goalSingleRoleHandler_f5vgr_b0b0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public goalSingleRoleHandler_f5vgr_b0b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fdL, "goal"), child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fdL, "goal"), child));
      installCellInfo(child, editorCell);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new SChildSubstituteInfo(editorCell, myNode, MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fdL, "goal"), child));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("goal");
      }
      Style style = new StyleImpl();
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
      editorCell.getStyle().putAll(style);
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca5fdL, "goal")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_goal");
        installCellInfo(null, editorCell);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no goal>";
    }
  }
  private EditorCell createRefNode_f5vgr_c0b0() {
    SingleRoleCellProvider provider = new Feature_EditorBuilder_a.benefitSingleRoleHandler_f5vgr_c0b0(myNode, MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca600L, "benefit"), getEditorContext());
    return provider.createCell();
  }
  private static class benefitSingleRoleHandler_f5vgr_c0b0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public benefitSingleRoleHandler_f5vgr_c0b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca600L, "benefit"), child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca600L, "benefit"), child));
      installCellInfo(child, editorCell);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new SChildSubstituteInfo(editorCell, myNode, MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca600L, "benefit"), child));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("benefit");
      }
      Style style = new StyleImpl();
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
      editorCell.getStyle().putAll(style);
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), MetaAdapterFactory.getContainmentLink(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L, 0x255fdd27325ca600L, "benefit")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_benefit");
        installCellInfo(null, editorCell);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no benefit>";
    }
  }
  private EditorCell createRefNode_f5vgr_c0() {
    SingleRoleCellProvider provider = new Feature_EditorBuilder_a.deleteButtonSingleRoleHandler_f5vgr_c0(myNode, MetaAdapterFactory.getContainmentLink(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L, 0x2bedf8479e5786a3L, "deleteButton"), getEditorContext());
    return provider.createCell();
  }
  private static class deleteButtonSingleRoleHandler_f5vgr_c0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public deleteButtonSingleRoleHandler_f5vgr_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L, 0x2bedf8479e5786a3L, "deleteButton"), child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L, 0x2bedf8479e5786a3L, "deleteButton"), child));
      installCellInfo(child, editorCell);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new SChildSubstituteInfo(editorCell, myNode, MetaAdapterFactory.getContainmentLink(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L, 0x2bedf8479e5786a3L, "deleteButton"), child));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("deleteButton");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), MetaAdapterFactory.getContainmentLink(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L, 0x2bedf8479e5786a3L, "deleteButton")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_deleteButton");
        installCellInfo(null, editorCell);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no deleteButton>";
    }
  }
}
