package UserStories.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Benefit = 0;
  public static final int Feature = 1;
  public static final int FeatureSet = 2;
  public static final int Goal = 3;
  public static final int Persona = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L);
    builder.put(0x255fdd27325ca5faL, Benefit);
    builder.put(0x135655a0a9cb0575L, Feature);
    builder.put(0x255fdd27325dd247L, FeatureSet);
    builder.put(0x255fdd27325ca5f7L, Goal);
    builder.put(0x255fdd27325ca5f4L, Persona);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
