package UserStories.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBenefit = createDescriptorForBenefit();
  /*package*/ final ConceptDescriptor myConceptFeature = createDescriptorForFeature();
  /*package*/ final ConceptDescriptor myConceptFeatureSet = createDescriptorForFeatureSet();
  /*package*/ final ConceptDescriptor myConceptGoal = createDescriptorForGoal();
  /*package*/ final ConceptDescriptor myConceptPersona = createDescriptorForPersona();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBenefit, myConceptFeature, myConceptFeatureSet, myConceptGoal, myConceptPersona);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Benefit:
        return myConceptBenefit;
      case LanguageConceptSwitch.Feature:
        return myConceptFeature;
      case LanguageConceptSwitch.FeatureSet:
        return myConceptFeatureSet;
      case LanguageConceptSwitch.Goal:
        return myConceptGoal;
      case LanguageConceptSwitch.Persona:
        return myConceptPersona;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForBenefit() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserStories", "Benefit", 0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5faL);
    b.class_(false, false, false);
    b.origin("r:7432e323-350c-4bf7-97d1-cc74d812b853(UserStories.structure)/2693114262609241594");
    b.prop("text", 0x255fdd27325ca705L, "2693114262609241861");
    b.alias("so that");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFeature() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserStories", "Feature", 0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L);
    b.origin("r:7432e323-350c-4bf7-97d1-cc74d812b853(UserStories.structure)/1393395283249530229");
    b.aggregate("persona", 0x255fdd27325ca5fbL).target(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5f4L).optional(false).ordered(true).multiple(false).origin("2693114262609241595").done();
    b.aggregate("goal", 0x255fdd27325ca5fdL).target(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5f7L).optional(false).ordered(true).multiple(false).origin("2693114262609241597").done();
    b.aggregate("benefit", 0x255fdd27325ca600L).target(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5faL).optional(false).ordered(true).multiple(false).origin("2693114262609241600").done();
    b.alias("Feature");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFeatureSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserStories", "FeatureSet", 0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325dd247L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7432e323-350c-4bf7-97d1-cc74d812b853(UserStories.structure)/2693114262609318471");
    b.aggregate("features", 0x255fdd27325dd24aL).target(0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x135655a0a9cb0575L).optional(true).ordered(true).multiple(true).origin("2693114262609318474").done();
    b.alias("Feature set");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGoal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserStories", "Goal", 0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5f7L);
    b.class_(false, false, false);
    b.origin("r:7432e323-350c-4bf7-97d1-cc74d812b853(UserStories.structure)/2693114262609241591");
    b.prop("text", 0x255fdd27325ca5f8L, "2693114262609241592");
    b.alias("I want");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersona() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("UserStories", "Persona", 0x7ff1fe9157924b98L, 0xbc3d7eb9c54f1ee3L, 0x255fdd27325ca5f4L);
    b.class_(false, false, false);
    b.origin("r:7432e323-350c-4bf7-97d1-cc74d812b853(UserStories.structure)/2693114262609241588");
    b.prop("text", 0x255fdd27325ca5f5L, "2693114262609241589");
    b.alias("As");
    return b.create();
  }
}
